instance_name = "webpage"
security_group_name = "mysecurity"
bucket_name = "komalsuthar"
private_key_location_in_pem = "C:/Users/Education/Downloads/mykey.pem"
image_name = "image.jpg"
key_name = "mykey"